name: build-packages-file

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:focal
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y curl git ruby-faraday ruby-json ruby-octokit
    - name: Make packages.json
      run: |
        git config --global user.email "myrmecocystus+ropenscibot@gmail.com"
        git config --global user.name "ropenscibot"
        bash git_urls.sh
        head packages.json
